### ISSUE TITLE
octodns 1.x

### ISSUE THREAD

**Issue by jacobw** [sukiyaki/octodns-netbox#42]
Octodns 1.x has been out for a while now. Are there any plans to support it?

I see the renovate bot has a PR but I don't understand why it's failing sorry.

**Comment by mochipon** [comment]
I apologize for the delay in responding.

I have released v0.3.0, updating all dependencies to the latest versions. Please give it a try.

I'm closing this issue for now, but if you encounter any issues, please let us know.
